### ISSUE TITLE
svc -h and svc -k are not working for davaz.com

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#14]
1. Trying to restart davaz.com with `svc -h /service/davaz.com` does not result in starting the service.
2. If I then do `svc -k /service/davaz.com` the service is not properly killed.
3. The service is then still bound to port 8007 and the error message is: `Address already in use - bind(2) for 127.0.0.1:8007 (Errno::EADDRINUSE)`
4. I then have to search for the process with `sudo netstat -tulpn | grep 8007`
5. And then kill PID with `sudo kill -9 32568`
6. This is super annoying.
7. Could this be related to #13?

**Comment by ngiger** [comment]
But why? The ruby brick seems to listen correctly to the HUP signal. See here:

```bash
$ sudo svstat /service/davaz.com/
/service/davaz.com/: up (pid 4027) 6 seconds
$ sudo kill -HUP 4027; sleep 3; sudo svstat /service/davaz.com/
/service/davaz.com/: up (pid 4067) 3 seconds
```

Therefore my question is. Why does svc -h not send correctly a HUP signal to the webrick process?
