### ISSUE TITLE
Login via Firefox does not work

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#19]
1. Logging in via Firefox does not work.
2. Logging in via Chrome, Edge and Safari works fine.
3. It seems that this directive does not work:
4. https://github.com/zdavatz/davaz.com/commit/350fbb03a5dc976c6e97c1425ae4b23baae428ce
5. `Header always set Content-Security-Policy "upgrade-insecure-requests;"`

**Comment by zdavatz** [comment]
For reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1700359

**Comment by zdavatz** [comment]
Mit diesem Commit kann man wieder einloggen auf Firefox, die Felder sind aber nicht editierbar:
1. Eintrag wählen: https://davaz.com/en/works/movies/#1706
2. Die Felder können aber nicht editiert werden:
![latest-screenshot](https://user-images.githubusercontent.com/4953/119943696-abe5e480-bf93-11eb-8598-836ff16f5018.png)
3. Wenn man eingeloggt ist, muss man die Felder editieren können. Siehe auch:

**Comment by b123400** [comment]
Alles sind editierbar für mich.

https://user-images.githubusercontent.com/127193/120063826-17b77280-c0a4-11eb-9e5e-38c1b39d3960.mp4

**Comment by zdavatz** [comment]
Ist das Firefox bei Dir? Dann lösche ich mal den Cache und die Cookies.

**Comment by b123400** [comment]
Ja, beide Firefox und Chrome

**Comment by zdavatz** [comment]
Danke, nach dem löschen vom Cache klappt es!

**Comment by zdavatz** [comment]
Do not forget to do `sudo a2enmod headers` to enable the Headers if you are on Ubuntu.
