### ISSUE TITLE
Delete Art Object not working

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#20]
1. Login to Davaz.com
2. Select Art Object: https://davaz.com/en/works/movies/#1858
3. Delete the Art Object with the Button 
4. <img width="81" alt="Bildschirmfoto 2021-04-04 um 21 53 13" src="https://user-images.githubusercontent.com/4953/113519978-33b10300-9590-11eb-81e8-cb070f5d4e80.png">
4. Results in
5. <img width="1417" alt="Bildschirmfoto 2021-04-04 um 21 48 44" src="https://user-images.githubusercontent.com/4953/113519900-8b02a380-958f-11eb-939b-b3870ddf5461.png">

**Comment by ngiger** [comment]
Ich konnte auf oddb-ci2 /var/www/davaz.com in 1,5h nicht zum Laufen bringen.
Deshalb lokal bei mir auf einem Debian Rechner mit Kopie der MySQL-DB, /var/www/davaz.com/etc und /var/www/davaz.com/doc zum Laufen gebracht (0,5h Aufwand).
Bei mir ging dann das Delete ohne Problem, aber da das Objekt nicht mehr vorhanden war, kam es zu obigen Fehler.
Dies musste in htmlgrid geschehen. Testfall dazu erstellt. (Aufwand 1.0h)
Werde neue htmlgrid-Version erstellen.

**Comment by zdavatz** [comment]
Danke!

**Comment by zdavatz** [comment]
Bitte die neue gem Version gleich installieren.

**Comment by ngiger** [comment]
Habe ich gemacht. 

Du solltest meine Anpassungen noch übernehmen und den diff 

iff --git a/src/view/_partial/textblock.rb b/src/view/_partial/textblock.rb
index 92243f5..c2ff107 100644
--- a/src/view/_partial/textblock.rb
+++ b/src/view/_partial/textblock.rb
@@ -168,7 +168,7 @@ module DaVaz::View

def url_to_html(context)
parsed = URI.parse(@model.url)
-      parsed = URI.parse('http://' + @model.url) unless parsed.scheme
+      parsed = URI.parse('https://' + @model.url) unless parsed.scheme
context.div('class' => 'block-url') {
context.a(
'href'   => parsed,

auch dort committen.

Es gibt aber noch diverse andere Ort unter dem Verzeichnis src, wo http anstelle von https drin steht.

Totaler Aufwand für diese Ticket war 3.75h

**Comment by zdavatz** [comment]
Ich verstehe nicht was Du meinst. Kannst Du diesen Patch bitte auch commiten und auf dem Fastpower via git pull installieren?

**Comment by zdavatz** [comment]
Neu kriege ich diesen Error:

![Bildschirmfoto 2021-04-14 um 20 54 12](https://user-images.githubusercontent.com/4953/114763907-a033bb00-9d63-11eb-8a45-2bba044c62db.png)

**Comment by zdavatz** [comment]
These are the [Chome-Web-Drivers](https://chromedriver.storage.googleapis.com/index.html?path=90.0.4430.24/) for Selenium/Watir

**Comment by ngiger** [comment]
Spec Tests laufen auf meinem Rechner wieder (nur chromium, nicht firefox).
Habe folgende 5 Fehler:

<pre>

1) Failure:
TestShop#test_checkout [/opt/src/davaz.com/test/feature/shop_test.rb:207]:
browser text should match Your order has been succesfully sent. but is 
NoMethodError at /en/communication
undefined method `mailer' for #<RCLConf::RCLConf:0x0000000002c7a928>
<...>
2) Failure:
TestDrawings#test_admin_drawings_canceling_of_add_new_serie [/opt/src/davaz.com/test/support/authentication.rb:26]:
Could not log in. login_email-Field must no longer be present!

3) Failure:
TestMovies#test_admin_movies_update_description_text_by_wysiwyg_editor [/opt/src/davaz.com/test/support/authentication.rb:26]:
Could not log in. login_email-Field must no longer be present!

4) Failure:
TestMovies#test_login_in_to_browsers [/opt/src/davaz.com/test/support/authentication.rb:26]:
Could not log in. login_email-Field must no longer be present!

5) Failure:
TestMovies#test_login_then_logout [/opt/src/davaz.com/test/support/authentication.rb:26]:
Could not log in. login_email-Field must no longer be present!

6) Error:
TestValidator#test_validate_article:
ArgumentError: wrong number of arguments (given 0, expected 2)
/opt/src/davaz.com/src/util/pw_server.rb:78:in `generate_pw_entry'
/opt/src/davaz.com/test/validator_test.rb:9:in `setup'

7) Failure:
TestNewArtObject#test_new_artobject_creation_with_validation_error [/opt/src/davaz.com/test/support/authentication.rb:26]:
Could not log in. login_email-Field must no longer be present!

8) Failure:
TestNewArtObject#test_new_artobject_creation [/opt/src/davaz.com/test/support/authentication.rb:26]:
Could not log in. login_email-Field must no longer be present!

9) Error:
TestGallery#test_gallery:
Watir::Wait::TimeoutError: timed out after 5 seconds, waiting for true condition on #<Watir::Div: located: false; {:id=>"show_container", :tag_name=>"div"} --> {:id=>"ywesee_widget_rack_2", :tag_name=>"div"}>
/opt/src/davaz.com/vendor/bundle/ruby/2.6.0/gems/watir-6.18.0/lib/watir/wait.rb:46:in `until'
/opt/src/davaz.com/vendor/bundle/ruby/2.6.0/gems/watir-6.18.0/lib/watir/wait.rb:125:in `wait_until'
/opt/src/davaz.com/test/test_helper.rb:28:in `wait_until'
/opt/src/davaz.com/test/feature/gallery_test.rb:39:in `test_gallery'

27 runs, 118 assertions, 7 failures, 2 errors, 4 skips
</pre>

**Comment by ngiger** [comment]
Watir Tests laufgen auf oddb.org nicht. Ruby stürzt mit einem Segmentation fault ab:

<pre>
/home/niklaus/git/davaz.com/vendor/ruby/3.0.0/gems/rclconf-1.0.0/lib/rclconf/rclconf.rb:59: warning: respond_to? is defined here
2 /home/niklaus/git/davaz.com/vendor/ruby/3.0.0/gems/mysql2-0.4.10/lib/mysql2/mysql2.so: [BUG] Segmentation fault at 0x0000000000000000
<...>
</pre>

[rake-test-2.log](https://github.com/zdavatz/davaz.com/files/6350196/rake-test-2.log)

Einen neuere Version vom rubygem mysql2 kompiliert auf oddb-ci2 nicht.

**Comment by zdavatz** [comment]
Welche Rubygem Version ist installiert?

**Comment by zdavatz** [comment]
Das habe ich laufen lassen `sudo emerge --config =dev-db/mariadb-10.5.9` und `/var/lib/mysql` sind jetzt initialisiert. Das alte Verzeichnis ist unter `/var/lib/mysql.old`

**Comment by zdavatz** [comment]
@ngiger sagt: 
> Ich komme aber via "mysql --user=root --password=niklaus" nicht rein. Hast Du eine Idee?

Die Lösung ist: `sudo /etc/init.d/mysql start`, dann klappt: `mysql --user=root --password=*******`

**Comment by b123400** [comment]
Ich habe ein PR gesendet, aber ich bin nicht sicher.
https://github.com/zdavatz/htmlgrid/pull/12

Wenn es gibt ein Problem, löschen es das Art Object eigentlich oder nicht?

**Comment by zdavatz** [comment]
Ich habe htmlgrid-1.2.2 released.

**Comment by zdavatz** [comment]
> Wenn es gibt ein Problem, löschen es das Art Object eigentlich oder nicht?

Zur Zeit wird das Art Object nicht gelöscht.

**Comment by zdavatz** [comment]
This is the full output: [davaz_delete_log_25.5.2021.txt](https://github.com/zdavatz/davaz.com/files/6536828/davaz_delete_log_25.5.2021.txt)
