### ISSUE TITLE
Panorama images throw XML error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#50]
1. The Panorama images throw the following error:
2. https://davaz.com/en/works/multiples/
3. ![Bildschirmfoto 2022-12-06 um 18 34 17](https://user-images.githubusercontent.com/4953/205982056-783b930d-e75e-455a-8ccd-aca2cd211e0d.png)
4. If possible lets upgrade to the lastest Pannellum version: https://github.com/mpetroff/pannellum
5. https://pannellum.org/download/

**Comment by zdavatz** [comment]
This seems to be the [error](https://validator.w3.org/check?uri=https%3A%2F%2Fdavaz.com%2Fresources%2Fjavascript%2Fpannellum%2Fpannellum.htm&charset=%28detect+automatically%29&doctype=HTML+4.01+Strict&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices):
```
Contradictory Parse Modes Detected!

The validator can process documents either as XML (for document types such as XHTML, SVG, etc.) or SGML (for HTML 4.01 and prior versions).

This document was served with HTTP headers declaring it as MIME Media Type (application/xhtml+xml), for which the parsing mode should be XML. However, the document's DOCTYPE Declaration indicates SGML mode.

Following the rules of Web Architecture, validation proceeded using the XML mode based on the Content-Type header.

Fixing this conflict involves either setting the Content-Type header, using a known document type or adding an XML declaration (in the case of XML-based documents).
```

**Comment by zdavatz** [comment]
`curl -v https://davaz.com/resources/javascript/pannellum/pannellum.htm` show the woring Content-Type: `Content-Type: application/xhtml+xml`

**Comment by b123400** [comment]
The apache configuration seems to be wrong, can you add the following config to `/etc/apache2/vhosts.d/davaz.com.conf`, inside `<VirtualHost *:443>`?

```
AddType "text/html; charset=utf-8" .htm
AddType "text/html; charset=utf-8" .html
AddDefaultCharset utf-8
```

**Comment by zdavatz** [comment]
Let me try! 🙏

**Comment by zdavatz** [comment]
Ok, if I move the file `/var/www/davaz.com/doc/resources/javascript/pannellum/panellum.htm` to the directory `/var/www/davaz.com/doc/` then the code is interpreted as html.

**Comment by zdavatz** [comment]
Ok, so this link seems to work as well:
https://davaz.com/doc/resources/javascript/pannellum/pannellum.htm?panorama=/resources/uploads/images/slide/8/228.jpeg&autoLoad=true&autoRotate=1

**Comment by zdavatz** [comment]
Changing to the full path in the source, works as well!
![latest-screenshot](https://user-images.githubusercontent.com/4953/206543409-7eebb67e-8ea4-4b0e-9ea5-9db424c33bb8.png)

**Comment by zdavatz** [comment]
fixed with: https://github.com/zdavatz/sbsm/commit/b310b17a8922a6028e65e4990236a08bab4cd5a1
