### ISSUE TITLE
Remove postgresql yus and pg-1.2.3.gem dependency

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#7]
1. Davaz.com still uses `yus` and `postgresql` as Login dependency. 
2. Remove postgres dependency and yus dependency.

**Comment by ngiger** [comment]
Wie soll man dann ein Login machen können, wenn nicht über yus?

**Comment by zdavatz** [comment]
Password Hash in einem File auf dem Server.

**Comment by ngiger** [comment]
Ich würde vorschlagen, das Gem bcrypt-ruby https://github.com/codahale/bcrypt-ruby/ zu verwenden. Eine Funktion zum Erstellen von user/password nur via CLI zur Verfügung stellen und die Eingaben in einer YAML-Datei zu speichern.
Braucht es zusätzlich noch die Zugehörigkeit zu Gruppen wie User, Admin? Wenn ja, welche?

**Comment by zdavatz** [comment]
Nein. Nur ein User Login.

**Comment by zdavatz** [comment]
> Ich würde vorschlagen, das Gem bcrypt-ruby https://github.com/codahale/bcrypt-ruby/ zu verwenden. Eine Funktion zum Erstellen von user/password nur via CLI zur Verfügung stellen und die Eingaben in einer YAML-Datei zu speichern.

Oder noch einfacher so: `echo -n "passwort1234" | openssl dgst -sha256`

**Comment by zdavatz** [comment]
The login Token should be the Password Hash: https://github.com/zdavatz/davaz.com/blob/master/src/util/session.rb#L63

**Comment by zdavatz** [comment]
`bundle install`still requires Postgresql `pg-1.2.3.gem`. Why? That should be gone with the removal of `yus`.
