### ISSUE TITLE
Upgrade Davaz.com to Ruby 3.0.0

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#8]
Davaz.com needs to be upgraded to Ruby 3.0.0

**Comment by ngiger** [comment]
This one is easy and work without yus fine. If you have ruby 3.0 installed with the binary name ruby then the following steps do it:
```cd /path/to/checkout
rm Gemfile.lock
echo "gem 'webrick'>> Gemfile # needed for Ruby 3.0 as no longer part of core
bundle install
sudo -u apache /usr/local/bin/bundle exec rackup config.ru --host 192.168.0.75
```
192.168.0.75 is ip of host on my local network to access
Will fail as soon as you want to login via yus.

**Comment by zdavatz** [comment]
How is this related to upgrading davaz.com to Ruby 3.0.0?

**Comment by ngiger** [comment]
You must upgrade the gems for Ruby 3.0, as some old versions are not compatible with ruby 3.0.
The 'webrick' gem is no longer bundled with ruby 3.0, see https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
Rackup config options are the same as for Rubies 2.x
